version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: fiducia_mvp
      POSTGRES_USER: fiducia_user
      POSTGRES_PASSWORD: fiducia_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fiducia_user -d fiducia_mvp"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Separate test database container for complete isolation
  postgres_test:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: fiducia_mvp_test
      POSTGRES_USER: fiducia_user
      POSTGRES_PASSWORD: fiducia_password
    ports:
      - "5433:5432"  # Different port
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fiducia_user -d fiducia_mvp_test"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - testing  # Only start when testing profile is active

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Test Redis (optional - for complete isolation)
  redis_test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - testing

volumes:
  postgres_data:
  redis_data:
  postgres_test_data:
  redis_test_data:
